// @generated by scripts/generate-xote-icons.mjs — do not edit manually.

/* Inline icons, so a copied component needs no icon dependency. The artwork is
   lucide, the same set the React registries pull from lucide-react. */

module Svg = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
    ~children: View.node,
  ) =>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      class=?{className}
      role=?{role}
      ariaLabel=?{ariaLabel}
      attrs=[View.optionalAttr("data-slot", dataSlot), View.optionalAttr("data-icon", dataIcon)]>
      {children}
    </svg>
}

module AlertCircle = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="12" cy="12" r="10" />
      <line x1="12" x2="12" y1="8" y2="12" />
      <line x1="12" x2="12.01" y1="16" y2="16" />
    </Svg>
}

module AlertTriangle = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" />
      <path d="M12 9v4" />
      <path d="M12 17h.01" />
    </Svg>
}

module Archive = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <rect width="20" height="5" x="2" y="3" rx="1" />
      <path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8" />
      <path d="M10 12h4" />
    </Svg>
}

module ArrowDown = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M12 5v14" />
      <path d="m19 12-7 7-7-7" />
    </Svg>
}

module ArrowLeft = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </Svg>
}

module ArrowRight = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </Svg>
}

module ArrowUp = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </Svg>
}

module ArrowUpRight = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M7 7h10v10" />
      <path d="M7 17 17 7" />
    </Svg>
}

module AudioLines = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M2 10v3" />
      <path d="M6 6v11" />
      <path d="M10 3v18" />
      <path d="M14 8v7" />
      <path d="M18 5v13" />
      <path d="M22 10v3" />
    </Svg>
}

module AudioWaveform = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M2 13a2 2 0 0 0 2-2V7a2 2 0 0 1 4 0v13a2 2 0 0 0 4 0V4a2 2 0 0 1 4 0v13a2 2 0 0 0 4 0v-4a2 2 0 0 1 2-2" />
    </Svg>
}

module BadgeCheck = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
      <path d="m9 12 2 2 4-4" />
    </Svg>
}

module Bell = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M10.268 21a2 2 0 0 0 3.464 0" />
      <path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326" />
    </Svg>
}

module Bluetooth = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m7 7 10 10-5 5V2l5 5L7 17" />
    </Svg>
}

module Bold = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M6 12h9a4 4 0 0 1 0 8H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h7a4 4 0 0 1 0 8" />
    </Svg>
}

module BookOpen = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M12 5v16" />
      <path d="M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z" />
    </Svg>
}

module Bookmark = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z" />
    </Svg>
}

module Bot = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </Svg>
}

module Building2 = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M10 12h4" />
      <path d="M10 8h4" />
      <path d="M14 21v-3a2 2 0 0 0-4 0v3" />
      <path d="M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2" />
      <path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16" />
    </Svg>
}

module Calculator = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <rect width="16" height="20" x="4" y="2" rx="2" />
      <line x1="8" x2="16" y1="6" y2="6" />
      <line x1="16" x2="16" y1="14" y2="18" />
      <path d="M16 10h.01" />
      <path d="M12 10h.01" />
      <path d="M8 10h.01" />
      <path d="M12 14h.01" />
      <path d="M8 14h.01" />
      <path d="M12 18h.01" />
      <path d="M8 18h.01" />
    </Svg>
}

module Calendar = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M8 2v3" />
      <path d="M16 2v3" />
      <rect x="3" y="3" width="18" height="18" rx="2" />
      <path d="M3 9h18" />
    </Svg>
}

module CalendarPlus = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M16 18h6" />
      <path d="M16 2v3" />
      <path d="M19 15v6" />
      <path d="M21 11.5V5a2 2 0 00-2-2H5a2 2 0 00-2 2v14a2 2 0 002 2h8.3" />
      <path d="M3 9h18" />
      <path d="M8 2v3" />
    </Svg>
}

module Check = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M20 6 9 17l-5-5" />
    </Svg>
}

module CheckCircle2 = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M21.801 10A10 10 0 1 1 17 3.335" />
      <path d="m9 11 3 3L22 4" />
    </Svg>
}

module ChevronDown = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m6 9 6 6 6-6" />
    </Svg>
}

module ChevronLeft = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m15 18-6-6 6-6" />
    </Svg>
}

module ChevronRight = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m9 18 6-6-6-6" />
    </Svg>
}

module ChevronUp = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m18 15-6-6-6 6" />
    </Svg>
}

module ChevronsLeft = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m11 17-5-5 5-5" />
      <path d="m18 17-5-5 5-5" />
    </Svg>
}

module ChevronsRight = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m6 17 5-5-5-5" />
      <path d="m13 17 5-5-5-5" />
    </Svg>
}

module ChevronsUpDown = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m7 15 5 5 5-5" />
      <path d="m7 9 5-5 5 5" />
    </Svg>
}

module CircleAlert = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="12" cy="12" r="10" />
      <line x1="12" x2="12" y1="8" y2="12" />
      <line x1="12" x2="12.01" y1="16" y2="16" />
    </Svg>
}

module CircleCheck = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </Svg>
}

module CircleDashed = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M10.1 2.182a10 10 0 0 1 3.8 0" />
      <path d="M13.9 21.818a10 10 0 0 1-3.8 0" />
      <path d="M17.609 3.721a10 10 0 0 1 2.69 2.7" />
      <path d="M2.182 13.9a10 10 0 0 1 0-3.8" />
      <path d="M20.279 17.609a10 10 0 0 1-2.7 2.69" />
      <path d="M21.818 10.1a10 10 0 0 1 0 3.8" />
      <path d="M3.721 6.391a10 10 0 0 1 2.7-2.69" />
      <path d="M6.391 20.279a10 10 0 0 1-2.69-2.7" />
    </Svg>
}

module CircleFadingPlus = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M12 2a10 10 0 0 1 7.38 16.75" />
      <path d="M12 8v8" />
      <path d="M16 12H8" />
      <path d="M2.5 8.875a10 10 0 0 0-.5 3" />
      <path d="M2.83 16a10 10 0 0 0 2.43 3.4" />
      <path d="M4.636 5.235a10 10 0 0 1 .891-.857" />
      <path d="M8.644 21.42a10 10 0 0 0 7.631-.38" />
    </Svg>
}

module ClipboardPaste = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M11 14h10" />
      <path d="M16 4h2a2 2 0 0 1 2 2v1.344" />
      <path d="m17 18 4-4-4-4" />
      <path d="M8 4H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 1.793-1.113" />
      <rect x="8" y="2" width="8" height="4" rx="1" />
    </Svg>
}

module Clock = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="12" cy="12" r="10" />
      <path d="M12 6v6l4 2" />
    </Svg>
}

module Clock2 = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="12" cy="12" r="10" />
      <path d="M12 6v6l4-2" />
    </Svg>
}

module Code = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m16 18 6-6-6-6" />
      <path d="m8 6-6 6 6 6" />
    </Svg>
}

module Command = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3" />
    </Svg>
}

module Copy = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
      <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
    </Svg>
}

module CornerDownLeft = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M20 4v7a4 4 0 0 1-4 4H4" />
      <path d="m9 10-5 5 5 5" />
    </Svg>
}

module CreditCard = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </Svg>
}

module Dot = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="12" cy="12" r="1" />
    </Svg>
}

module Download = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M12 15V3" />
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <path d="m7 10 5 5 5-5" />
    </Svg>
}

module ExternalLink = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M15 3h6v6" />
      <path d="M10 14 21 3" />
      <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
    </Svg>
}

module Eye = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0" />
      <circle cx="12" cy="12" r="3" />
    </Svg>
}

module EyeOff = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49" />
      <path d="M14.084 14.158a3 3 0 0 1-4.242-4.242" />
      <path d="M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143" />
      <path d="m2 2 20 20" />
    </Svg>
}

module File = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z" />
      <path d="M14 2v5a1 1 0 0 0 1 1h5" />
    </Svg>
}

module FileCode = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z" />
      <path d="M14 2v5a1 1 0 0 0 1 1h5" />
      <path d="M10 12.5 8 15l2 2.5" />
      <path d="m14 12.5 2 2.5-2 2.5" />
    </Svg>
}

module FileText = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z" />
      <path d="M14 2v5a1 1 0 0 0 1 1h5" />
      <path d="M10 9H8" />
      <path d="M16 13H8" />
      <path d="M16 17H8" />
    </Svg>
}

module Folder = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    </Svg>
}

module FolderOpen = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2" />
    </Svg>
}

module FolderPlus = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M12 10v6" />
      <path d="M9 13h6" />
      <path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    </Svg>
}

module FolderSearch = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M10.7 20H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H20a2 2 0 0 1 2 2v4.1" />
      <path d="m21 21-1.9-1.9" />
      <circle cx="17" cy="17" r="3" />
    </Svg>
}

module Forward = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m15 17 5-5-5-5" />
      <path d="M4 18v-2a4 4 0 0 1 4-4h12" />
    </Svg>
}

module Frame = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <line x1="22" x2="2" y1="6" y2="6" />
      <line x1="22" x2="2" y1="18" y2="18" />
      <line x1="6" x2="6" y1="2" y2="22" />
      <line x1="18" x2="18" y1="2" y2="22" />
    </Svg>
}

module GalleryVerticalEnd = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M7 2h10" />
      <path d="M5 6h14" />
      <rect width="18" height="12" x="3" y="10" rx="2" />
    </Svg>
}

module Globe = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />
      <path d="M2 12h20" />
    </Svg>
}

module HelpCircle = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="12" cy="12" r="10" />
      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
      <path d="M12 17h.01" />
    </Svg>
}

module Home = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8" />
      <path d="M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
    </Svg>
}

module Image = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </Svg>
}

module Inbox = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <polyline points="22 12 16 12 14 15 10 15 8 12 2 12" />
      <path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z" />
    </Svg>
}

module Info = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </Svg>
}

module Italic = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <line x1="19" x2="10" y1="4" y2="4" />
      <line x1="14" x2="5" y1="20" y2="20" />
      <line x1="15" x2="9" y1="4" y2="20" />
    </Svg>
}

module Keyboard = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M10 8h.01" />
      <path d="M12 12h.01" />
      <path d="M14 8h.01" />
      <path d="M16 12h.01" />
      <path d="M18 8h.01" />
      <path d="M6 8h.01" />
      <path d="M7 16h10" />
      <path d="M8 12h.01" />
      <rect width="20" height="16" x="2" y="4" rx="2" />
    </Svg>
}

module Languages = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m5 8 6 6" />
      <path d="m4 14 6-6 2-3" />
      <path d="M2 5h12" />
      <path d="M7 2h1" />
      <path d="m22 22-5-10-5 10" />
      <path d="M14 18h6" />
    </Svg>
}

module Layout = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <rect width="7" height="18" x="3" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="14" rx="1" />
    </Svg>
}

module LayoutGrid = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <rect width="7" height="7" x="3" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="14" rx="1" />
      <rect width="7" height="7" x="3" y="14" rx="1" />
    </Svg>
}

module LifeBuoy = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="12" cy="12" r="10" />
      <path d="m4.93 4.93 4.24 4.24" />
      <path d="m14.83 9.17 4.24-4.24" />
      <path d="m14.83 14.83 4.24 4.24" />
      <path d="m9.17 14.83-4.24 4.24" />
      <circle cx="12" cy="12" r="4" />
    </Svg>
}

module Link2 = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M9 17H7A5 5 0 0 1 7 7h2" />
      <path d="M15 7h2a5 5 0 1 1 0 10h-2" />
      <line x1="8" x2="16" y1="12" y2="12" />
    </Svg>
}

module List = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M3 5h.01" />
      <path d="M3 12h.01" />
      <path d="M3 19h.01" />
      <path d="M8 5h13" />
      <path d="M8 12h13" />
      <path d="M8 19h13" />
    </Svg>
}

module ListFilter = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M2 5h20" />
      <path d="M6 12h12" />
      <path d="M9 19h6" />
    </Svg>
}

module Loader = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M21 12a9 9 0 1 1-6.219-8.56" />
    </Svg>
}

module Loader2 = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M21 12a9 9 0 1 1-6.219-8.56" />
    </Svg>
}

module LogOut = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m16 17 5-5-5-5" />
      <path d="M21 12H9" />
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
    </Svg>
}

module Mail = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7" />
      <rect x="2" y="4" width="20" height="16" rx="2" />
    </Svg>
}

module MailCheck = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M22 13V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h8" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
      <path d="m16 19 2 2 4-4" />
    </Svg>
}

module Map = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z" />
      <path d="M15 5.764v15" />
      <path d="M9 3.236v15" />
    </Svg>
}

module Maximize = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M8 3H5a2 2 0 0 0-2 2v3" />
      <path d="M21 8V5a2 2 0 0 0-2-2h-3" />
      <path d="M3 16v3a2 2 0 0 0 2 2h3" />
      <path d="M16 21h3a2 2 0 0 0 2-2v-3" />
    </Svg>
}

module MessageSquare = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z" />
    </Svg>
}

module Mic = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M12 19v3" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <rect x="9" y="2" width="6" height="13" rx="3" />
    </Svg>
}

module Minimize = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M8 3v3a2 2 0 0 1-2 2H3" />
      <path d="M21 8h-3a2 2 0 0 1-2-2V3" />
      <path d="M3 16h3a2 2 0 0 1 2 2v3" />
      <path d="M16 21v-3a2 2 0 0 1 2-2h3" />
    </Svg>
}

module Minus = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M5 12h14" />
    </Svg>
}

module Monitor = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <rect width="20" height="14" x="2" y="3" rx="2" />
      <line x1="8" x2="16" y1="21" y2="21" />
      <line x1="12" x2="12" y1="17" y2="21" />
    </Svg>
}

module Moon = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401" />
    </Svg>
}

module MoreHorizontal = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </Svg>
}

module OctagonX = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m15 9-6 6" />
      <path d="M2.586 16.726A2 2 0 0 1 2 15.312V8.688a2 2 0 0 1 .586-1.414l4.688-4.688A2 2 0 0 1 8.688 2h6.624a2 2 0 0 1 1.414.586l4.688 4.688A2 2 0 0 1 22 8.688v6.624a2 2 0 0 1-.586 1.414l-4.688 4.688a2 2 0 0 1-1.414.586H8.688a2 2 0 0 1-1.414-.586z" />
      <path d="m9 9 6 6" />
    </Svg>
}

module Palette = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z" />
      <circle cx="13.5" cy="6.5" r=".5" fill="currentColor" />
      <circle cx="17.5" cy="10.5" r=".5" fill="currentColor" />
      <circle cx="6.5" cy="12.5" r=".5" fill="currentColor" />
      <circle cx="8.5" cy="7.5" r=".5" fill="currentColor" />
    </Svg>
}

module PanelLeft = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M9 3v18" />
    </Svg>
}

module PanelLeftClose = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M9 3v18" />
      <path d="m16 15-3-3 3-3" />
    </Svg>
}

module PanelLeftOpen = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M9 3v18" />
      <path d="m14 9 3 3-3 3" />
    </Svg>
}

module Pencil = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z" />
      <path d="m15 5 4 4" />
    </Svg>
}

module PieChart = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M21 12c.552 0 1.005-.449.95-.998a10 10 0 0 0-8.953-8.951c-.55-.055-.998.398-.998.95v8a1 1 0 0 0 1 1z" />
      <path d="M21.21 15.89A10 10 0 1 1 8 2.83" />
    </Svg>
}

module Plus = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </Svg>
}

module Radio = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M16.247 7.761a6 6 0 0 1 0 8.478" />
      <path d="M19.075 4.933a10 10 0 0 1 0 14.134" />
      <path d="M4.925 19.067a10 10 0 0 1 0-14.134" />
      <path d="M7.753 16.239a6 6 0 0 1 0-8.478" />
      <circle cx="12" cy="12" r="2" />
    </Svg>
}

module RefreshCcw = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
      <path d="M3 3v5h5" />
      <path d="M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16" />
      <path d="M16 16h5v5" />
    </Svg>
}

module RefreshCw = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </Svg>
}

module Save = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z" />
      <path d="M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7" />
      <path d="M7 3v4a1 1 0 0 0 1 1h7" />
    </Svg>
}

module Scissors = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="6" cy="6" r="3" />
      <path d="M8.12 8.12 12 12" />
      <path d="M20 4 8.12 15.88" />
      <circle cx="6" cy="18" r="3" />
      <path d="M14.8 14.8 20 20" />
    </Svg>
}

module Search = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m21 21-4.34-4.34" />
      <circle cx="11" cy="11" r="8" />
    </Svg>
}

module Send = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z" />
      <path d="m21.854 2.147-10.94 10.939" />
    </Svg>
}

module Settings = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915" />
      <circle cx="12" cy="12" r="3" />
    </Svg>
}

module Settings2 = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M14 17H5" />
      <path d="M19 7h-9" />
      <circle cx="17" cy="17" r="3" />
      <circle cx="7" cy="7" r="3" />
    </Svg>
}

module Share = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M12 2v13" />
      <path d="m16 6-4-4-4 4" />
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
    </Svg>
}

module Shield = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
    </Svg>
}

module ShieldAlert = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
      <path d="M12 8v4" />
      <path d="M12 16h.01" />
    </Svg>
}

module Smile = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M15 10V9" />
      <path d="M16.472 15a6 6 0 01-8.943 0" />
      <path d="M9 10V9" />
      <circle cx="12" cy="12" r="10" />
    </Svg>
}

module SortAsc = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m3 8 4-4 4 4" />
      <path d="M7 4v16" />
      <path d="M11 12h4" />
      <path d="M11 16h7" />
      <path d="M11 20h10" />
    </Svg>
}

module Sparkles = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z" />
      <path d="M20 2v4" />
      <path d="M22 4h-4" />
      <circle cx="4" cy="20" r="2" />
    </Svg>
}

module SquareTerminal = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m7 11 2-2-2-2" />
      <path d="M11 13h4" />
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
    </Svg>
}

module Star = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z" />
    </Svg>
}

module Sun = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </Svg>
}

module Tag = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z" />
      <circle cx="7.5" cy="7.5" r=".5" fill="currentColor" />
    </Svg>
}

module Trash = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" />
      <path d="M3 6h18" />
      <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
    </Svg>
}

module Trash2 = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M10 11v6" />
      <path d="M14 11v6" />
      <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" />
      <path d="M3 6h18" />
      <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
    </Svg>
}

module TriangleAlert = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" />
      <path d="M12 9v4" />
      <path d="M12 17h.01" />
    </Svg>
}

module Underline = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M6 4v6a6 6 0 0 0 12 0V4" />
      <line x1="4" x2="20" y1="20" y2="20" />
    </Svg>
}

module User = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </Svg>
}

module Wallet = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1" />
      <path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4" />
    </Svg>
}

module X = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </Svg>
}

module ZoomIn = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="11" cy="11" r="8" />
      <line x1="21" x2="16.65" y1="21" y2="16.65" />
      <line x1="11" x2="11" y1="8" y2="14" />
      <line x1="8" x2="14" y1="11" y2="11" />
    </Svg>
}

module ZoomOut = {
  @xote.component
  let make = (
    ~className: option<string>=?,
    ~dataSlot: option<string>=?,
    ~dataIcon: option<string>=?,
    ~ariaLabel: option<string>=?,
    ~role: option<string>=?,
  ) =>
    <Svg ?className ?dataSlot ?dataIcon ?ariaLabel ?role>
      <circle cx="11" cy="11" r="8" />
      <line x1="21" x2="16.65" y1="21" y2="16.65" />
      <line x1="8" x2="14" y1="11" y2="11" />
    </Svg>
}
